version: 0.2
phases:
  install:
    commands:
      - echo "install step"
      - npm install
  pre_build:
    commands:
      - echo "pre_build step"
      - npm run test
  build:
    commands:
      - echo "build step"
      - npm run build
  post_build:
    commands:
      - echo "post_build step"
      - npm run deploy-storybook
