version: 2
jobs:
  # build job omitted for brevity
  install:
    working_directory: ~/repo
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: Install Packages
          command: npm install
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: Run Tests
          command: npm run test
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: Build Package
          command: npm run build
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/repo
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy storybook to S3
          command: npm run deploy-storybook -- --ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
