version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@0.1.18

executors:
  node:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Branch Name
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Package
          command: npm run build

  deploy-storybook:
    executor: node
    steps:
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - aws-s3/sync:
          from: ./.out
          to: 's3://uswds-react-preview.com'
          overwrite: true

  test-deploy:
    executor: node
    steps:
      - run:
          name: test branch again
          command: npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-storybook:
          requires:
            - build
          filters:
            branches:
              only: master
      - test-deploy:
          requires:
            - build
