version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Log Branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Package
          command: npm run build
  deploy:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy storybook to S3
          command: npm run deploy-storybook

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
          # test
