version: 2.1

executors:
  node:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo

jobs:
  ci-cd:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Package
          command: npm run build
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy storybook to S3
          command: npm run deploy-storybook

workflows:
  version: 2
  build-deploy:
    jobs:
      - ci-cd
      # - deploy:
      #     requires:
      #       - build
      # filters:
      #   branches:
      #     only: master
      # test
