version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@x.y

executors:
  node:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo

jobs:
  ci-cd:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Package
          command: npm run build
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - aws-cli/setup:
          profile-name: example
          aws-region: us-east-2
      - aws-s3/sync:
          from: ./.out
          to: 's3://uswds-react-preview.com'
          overwrite: true
      # - run:
      #     name: Deploy storybook to S3
      #     command: npm run deploy-storybook

workflows:
  version: 2
  build-deploy:
    jobs:
      - ci-cd:
          context: aws
      # - deploy:
      #     requires:
      #       - build
      # filters:
      #   branches:
      #     only: master
      # test
