version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@0.1.18

executors:
  node:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo

jobs:
  ci-cd:
    branches:
      only:
        - master
    executor: node
    steps:
      - checkout
      - run:
          name: Branch Name
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Package
          command: npm run build
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - aws-s3/sync:
          from: ./.out
          to: 's3://uswds-react-preview.com'
          overwrite: true

workflows:
  version: 2
  build-deploy:
    jobs:
      - ci-cd
